# Generated by Django 3.1.12 on 2021-07-06 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('works', '0002_auto_20210705_1725'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fingerprints', '0006_auto_20210705_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(max_length=50, verbose_name='نوع پست')),
                ('text', models.TextField(max_length=511, verbose_name='متن پست')),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts/', verbose_name='تصویر')),
                ('likes', models.IntegerField(default=0, verbose_name='تعداد لایک\u200cها')),
                ('fingerprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fingerprints.fingerprint', verbose_name='اثر')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='works.work', verbose_name='اثر')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.BooleanField(default=True, verbose_name='لایک شده')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post', verbose_name='پست')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'Like',
                'verbose_name_plural': 'Likes',
            },
        ),
    ]
