# Generated by Django 3.1.12 on 2021-08-17 10:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='uuid')),
                ('text', models.TextField(max_length=255, verbose_name='متن کامنت')),
                ('posted', models.BooleanField(default=True, verbose_name='بازنشر شده')),
                ('date_time', models.DateTimeField(auto_now=True, verbose_name='زمان')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='uuid')),
                ('liked', models.BooleanField(default=True, verbose_name='لایک شده')),
                ('date_time', models.DateTimeField(auto_now=True, verbose_name='زمان')),
            ],
            options={
                'verbose_name': 'Like',
                'verbose_name_plural': 'Likes',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='uuid')),
                ('post_type', models.CharField(choices=[('اثر جدید', 'اثر جدید'), ('گواهی زمانی جدید', 'گواهی زمانی جدید'), ('خبر جدید', 'خبر جدید'), ('خبر بازنشر شده', 'خبر بازنشر شده')], max_length=50, verbose_name='نوع پست')),
                ('text', models.TextField(max_length=511, verbose_name='متن پست')),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts/', verbose_name='تصویر')),
                ('draft', models.BooleanField(default=False, verbose_name='پیش\u200cنویس')),
                ('likes', models.IntegerField(default=0, verbose_name='تعداد لایک\u200cها')),
                ('comments', models.IntegerField(default=0, verbose_name='تعداد نظرها')),
                ('shares', models.IntegerField(default=0, verbose_name='تعداد به اشتراک گذاری\u200cها')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='uuid')),
                ('shared', models.BooleanField(default=True, verbose_name='بازنشر شده')),
                ('date_time', models.DateTimeField(auto_now=True, verbose_name='زمان')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post', verbose_name='پست')),
            ],
            options={
                'verbose_name': 'Share',
                'verbose_name_plural': 'Shares',
            },
        ),
    ]
