# Generated by Django 3.1.12 on 2021-07-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('اثر جدید', 'اثر جدید'), ('گواهی زمانی جدید', 'گواهی زمانی جدید'), ('خبر جدید', 'خبر جدید')], max_length=50, verbose_name='نوع پست'),
        ),
    ]
