# Generated by Django 3.1.12 on 2021-07-11 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210711_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='shared_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.post', verbose_name='خبر به اشتراک\u200cگذاری شده'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('اثر جدید', 'اثر جدید'), ('گواهی زمانی جدید', 'گواهی زمانی جدید'), ('خبر جدید', 'خبر جدید'), ('خبر به اشتراک\u200cگذاری شده', 'خبر به اشتراک\u200cگذاری شده')], max_length=50, verbose_name='نوع پست'),
        ),
    ]
