# Generated by Django 3.1.12 on 2021-07-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20210712_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='date_time',
            field=models.DateTimeField(auto_now=True, verbose_name='زمان'),
        ),
    ]
