# Generated by Django 3.1.12 on 2021-07-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20210721_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='shares',
            field=models.IntegerField(default=0, verbose_name='تعداد به اشتراک گذاری\u200cها'),
        ),
    ]
