# Generated by Django 3.1.12 on 2021-07-23 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.TextField(default=1, max_length=255, verbose_name='متن کامنت'),
            preserve_default=False,
        ),
    ]
