# Generated by Django 3.1.12 on 2021-07-23 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_comment_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='answerd_to',
            new_name='answered_to',
        ),
    ]
