# Generated by Django 3.1.12 on 2021-07-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='likes',
            field=models.JSONField(default={}, verbose_name='لایک\u200cهای کاربر'),
            preserve_default=False,
        ),
    ]
