# Generated by Django 3.1.12 on 2021-07-21 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210721_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='likes',
            field=models.JSONField(default=dict, verbose_name='لایک\u200cهای کاربر'),
        ),
        migrations.AlterField(
            model_name='user',
            name='shares',
            field=models.JSONField(default=dict, verbose_name='به\u200cاشتراک\u200cگذاری\u200cهای کاربر'),
        ),
    ]
