# Generated by Django 3.1.12 on 2021-06-28 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FingerPrint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fingerprint_work', to='works.work', verbose_name='اثر ')),
            ],
            options={
                'verbose_name': 'FingerPrint',
                'verbose_name_plural': 'FingerPrints',
            },
        ),
    ]
