# Generated by Django 3.1.12 on 2021-08-17 10:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FingerPrint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('fingerprint', models.CharField(max_length=255, verbose_name='اثرانگشت')),
                ('post_text', models.TextField(blank=True, max_length=1200, null=True, verbose_name='متن پست به روزرسانی')),
                ('date_time', models.DateTimeField(auto_now=True, verbose_name='تاریخ و زمان ثبت')),
                ('registered_on_list_blockchain', models.BooleanField(default=False, verbose_name='ثبت شده در بلاکچین به صورت گروهی')),
            ],
            options={
                'verbose_name': 'FingerPrint',
                'verbose_name_plural': 'FingerPrints',
            },
        ),
    ]
