# Generated by Django 3.1.12 on 2021-06-28 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
        ('fingerprints', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fingerprint',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fingerprintwork', to='works.work', verbose_name='اثر '),
        ),
    ]
