# Generated by Django 3.1.11 on 2021-07-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fingerprints', '0002_auto_20210628_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='fingerprint',
            name='date_time',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ و زمان ثبت'),
        ),
        migrations.AddField(
            model_name='fingerprint',
            name='fingerprint',
            field=models.CharField(default=None, max_length=255, verbose_name='اثرانگشت'),
            preserve_default=False,
        ),
    ]
