# Generated by Django 3.1.11 on 2021-07-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fingerprints', '0003_auto_20210705_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='fingerprint',
            name='registered_on_list_blockchain',
            field=models.BooleanField(default=None, verbose_name='ثبت شده در بلاکچین به صورت گروهی'),
            preserve_default=False,
        ),
    ]
