# Generated by Django 3.1.12 on 2021-07-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fingerprints', '0004_fingerprint_registered_on_list_blockchain'),
    ]

    operations = [
        migrations.AddField(
            model_name='fingerprint',
            name='post_text',
            field=models.TextField(blank=True, max_length=1200, null=True, verbose_name='متن پست به روزرسانی'),
        ),
    ]
