# Generated by Django 3.1.12 on 2021-07-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fingerprints', '0005_fingerprint_post_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fingerprint',
            name='registered_on_list_blockchain',
            field=models.BooleanField(default=False, verbose_name='ثبت شده در بلاکچین به صورت گروهی'),
        ),
    ]
