# Generated by Django 3.1.12 on 2021-07-11 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fingerprints', '0006_auto_20210705_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='fingerprint',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='کاربر'),
            preserve_default=False,
        ),
    ]
