# Generated by Django 3.1.12 on 2021-08-17 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('work_type', models.CharField(max_length=100, verbose_name='نوع اثر')),
                ('description', models.TextField(blank=True, null=True, verbose_name='درباره اثر')),
            ],
            options={
                'verbose_name': 'Work',
                'verbose_name_plural': 'Works',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='uuid')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('work_type', models.CharField(choices=[('شعر', 'شعر'), ('داستان', 'داستان'), ('سورس کد', 'فیلمنامه'), ('نمایشنامه', 'نمایشنامه'), ('نقاشی', 'نقاشی'), ('خوش\u200cنویسی', 'خوش\u200cنویسی'), ('طراحی', 'طراحی'), ('موسیقی', 'موسیقی'), ('سورس کد', 'سورس کد'), ('هنر دیجیتال', 'هنر دیجیتال'), ('محتوای دیجیتال', 'محتوای دیجیتال'), ('سایر', 'سایر')], max_length=100, verbose_name='نوع اثر')),
                ('description', models.TextField(blank=True, null=True, verbose_name='درباره اثر')),
                ('work_image', models.ImageField(upload_to='work_images/', verbose_name='تصویر شاخص اثر')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'Work',
                'verbose_name_plural': 'Works',
            },
        ),
    ]
