# Generated by Django 3.1.12 on 2021-07-05 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('work_type', models.CharField(max_length=100, verbose_name='نوع اثر')),
                ('description', models.TextField(blank=True, null=True, verbose_name='درباره اثر')),
            ],
            options={
                'verbose_name': 'Work',
                'verbose_name_plural': 'Works',
            },
        ),
        migrations.RemoveField(
            model_name='work',
            name='fingerprint',
        ),
        migrations.AddField(
            model_name='work',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='کاربر'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='work',
            name='work_image',
            field=models.ImageField(default=None, upload_to='work_images/', verbose_name='تصویر شاخص اثر'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='work',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='درباره اثر'),
        ),
    ]
