# Generated by Django 3.1.12 on 2021-07-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_auto_20210705_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='work_type',
            field=models.CharField(choices=[('شعر', 'شعر'), ('داستان', 'داستان'), ('سورس کد', 'فیلمنامه'), ('نمایشنامه', 'نمایشنامه'), ('نقاشی', 'نقاشی'), ('خوش\u200cنویسی', 'خوش\u200cنویسی'), ('طراحی', 'طراحی'), ('موسیقی', 'موسیقی'), ('سورس کد', 'سورس کد'), ('هنر دیجیتال', 'هنر دیجیتال'), ('محتوای دیجیتال', 'محتوای دیجیتال'), ('سایر', 'سایر')], max_length=100, verbose_name='نوع اثر'),
        ),
    ]
